### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by kusiLaw** [AbigiyaTY/Leaderboard#6]
Highlight :heavy_check_mark: 
- code follows dry
- nice design

Recommendation :+1: 
Good work so far but I recommend checking the margin of the page for a better user experience

happy coding :smile:

**Comment by TracyMuso** [comment]
# Hey @AbigiyaTY , the project looks great!
**A few suggestions**

- Please implement the function that displays the leader board whenever the window loads, that way people can see the scores the moment they navigate to your website.
- Please use a responsive design for your page elements, your elements overlap when the screen size is changed. This will provide a better user experience.
